export const DASHBOARD = "/dashboard";
// export const ADD_EMAIL_TEMPLATE = "/addEmailTemplate";
// export const DASHBOARD = "/dashboard";
// export const DASHBOARD = "/dashboard";
// export const DASHBOARD = "/dashboard";
// export const DASHBOARD = "/dashboard";
// export const DASHBOARD = "/dashboard";
// export const DASHBOARD = "/dashboard";
// export const DASHBOARD = "/dashboard";