export const DASHBOARD = "/dashboard";
export const CONTACT = "/contact";
export const ADD_EMAIL_TEMPLATE="/email/add"
export const ADD_SMS_TEMPLATE="/sms/add"
export const ADD_SIMPLE_EMAIL_TEMPLATE="/email/add/simple-email-template"
export const CREATE_SMS_TEMPLATE="/sms/add/sms-template"
export const CREATE_WHATSAPP_TEMPLATE="/sms/add/whatsapp-template"
export const CREATE_PUSH_TEMPLATE="/push/add/push-template"
export const ADD_ADVANCED_EMAIL_TEMPLATE="/email/add/advanced-email-template"
export const LIST_EMAIL_TEMPLATES="/email/list"
export const LIST_SMS_TEMPLATES="/sms/list"
export const LIST_PUSH_TEMPLATES="/push/list"

export const LIST_USERS="/users/list"
export const USERS_STATISTICS="/users/statistics"
export const EMAILS_STATISTICS="/email/statistics"
export const PROFILE="/profile"
export const SEND_EMAIL="/email/send"
export const SEND_SMS_SEPARATELY="/email/send-separately"
export const SEND_SMS="/sms/send"
export const SEND_WHATSAPP="/whatsapp/send"
export const SEND_EMAIL_SCHEDULED="/email/send/scheduled"
export const EDIT_EMAIL_TEMPLATE="/email/edit"
export const UPDATE_SMS_TEMPLATE="/sms/update"
export const UPDATE_PUSH_TEMPLATE="/push/update"
export const AUTHENTICATION="/authentication"
export const CALENDAR="/calendar"
export const SAVEDTEMPLATES="/saved-templates"

//docker exec -it db-postgres psql -U postgres -d Ms_Email_Notification
