version: "3.9"

services:

  eureka:
    build: ./EurekaServer
    ports:
      - "8761:8761"
    image: eureka:latest
    hostname: serviceregistry
    environment:
      - eureka.client.service-url.defaultZone=http://serviceregistry:8761/eureka/
    networks:
      - mynetwork  # Define a network for inter-service communication

  apiGateway:
    image: gatewayapi:latest
    build: ./APIGateway
    ports:
      - "8099:8099"
    environment:
      - eureka.client.service-url.defaultZone=http://serviceregistry:8761/eureka/
    depends_on:
      - eureka
    networks:
      - mynetwork



  auth:
    container_name: auth
    image: auth:latest
    build: ./ms_auth
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/Ms_Auth_Notification?useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - eureka.client.service-url.defaultZone=http://serviceregistry:8761/eureka/
    depends_on:
      - eureka
      - db-postgres
      - apiGateway
    networks:
      - mynetwork

  email:
    container_name: email
    image: email:latest
    build: ./ms_email
    ports:
      - "8091:8091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/Ms_Email_Notification?useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - eureka.client.service-url.defaultZone=http://serviceregistry:8761/eureka/
    depends_on:
      - eureka
      - db-postgres
      - apiGateway
    networks:
      - mynetwork

  sms:
    container_name: sms
    image: sms:latest
    build: ./ms_sms
    ports:
      - "9092:9092"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/Ms_SMS_Notification?useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - eureka.client.service-url.defaultZone=http://serviceregistry:8761/eureka/
    depends_on:
      - eureka
      - db-postgres
      - apiGateway
    networks:
      - mynetwork
      
  push:
      container_name: push
      image: push:latest
      build: ./ms_push
      ports:
        - "9093:9093"
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/Ms_PUSH_Notification?useSSL=false
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=admin
        - eureka.client.service-url.defaultZone=http://serviceregistry:8761/eureka/
      depends_on:
        - eureka
        - db-postgres
        - apiGateway
      networks:
        - mynetwork



  db-postgres:
    image: postgres:alpine
    container_name: db-postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - mynetwork



networks:
  mynetwork:    
    driver: bridge